### ISSUE TITLE
Persistent route issues

### ISSUE THREAD

**Issue by TaylorRoss** [TaylorRoss/FLCL-WEB#3]
Visiting any subdirectory via route when the page has not been initially loaded results in: "The resource you are looking for has been removed, had its name changed, or is temporarily unavailable"

Also occurs on landing page when smashing the FLCL icon then the home button.

**Comment by TheChrisRoss** [comment]
There is no single configuration that works for every server. The following sections describe configurations for some of the most popular servers. The list is by no means exhaustive, but should provide you with a good starting point.  In this case, IIS is the target and the web.config file which is placed in the site root (wwwroot) has been implemented.  

Will test fully with next push to production. 

Documentation for this approach can be found here:  https://angular.io/guide/deployment#fallback-configuration-examples

**Comment by TheChrisRoss** [comment]
Additional reading for this issue here: https://stackoverflow.com/questions/36630536/rewriting-a-url-in-an-azure-web-app

**Comment by TheChrisRoss** [comment]
Initial testing looks like the issue has been resolved.  I can indeed browse any page from a direct URL without having to have loaded the site first.  

@TaylorRoss please take a minute to test this from your browsers and report back your findings.  

Here's a few links for convenience;
http://www.flcltech.com/contact
http://www.flcltech.com/about
http://www.flcltech.com/services
